config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get "dashboad/index"

  resources :experiences
  mount Resque::Server.new, :at => "/resque"
  
  resources :rooms do 
    resources :messages
  end
  
  resources :users_jobs, only: [:index, :create] do 
    member do 
      get "apply"
      get "candidates"
      get "show"
      post "destroy", as: "destroy"
    end

  end

  resources :jobs do
    collection do 
      get "search" 
      get "search_with_category"
      get "my_opportunities"
    end 
  end
  
  resources :categories 

  devise_for :users, controllers: {registrations: "registrations"}
  root "home#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  get "back_lists/:id_job/job_create", 
    to: "back_lists#job_create", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "job_create"
  
  get "back_lists/:id_publicity/publicity_complaint", 
    to: "back_lists#publicity_complaint", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "back_lists_publicity_complaint"

    
  get "back_lists/:id_job/job_complaint", 
  to: "back_lists#job_complaint", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_job_complaint"

  
  get "back_lists/publicities", 
  to: "back_lists#publicities", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_publicities"

  get "back_lists/jobs", 
  to: "back_lists#jobs", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_jobs"

  get "back_lists", 
  to: "back_lists#index", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists"
  
   
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :users_jobs, dependent: :destroy
  has_many :users, through: :users_jobs

  has_one :job_complaint, dependent: :destroy

  validates_presence_of :title, :type_job, :content

  enum type_job: {Remota: "Remota", Presencial: "Presencial", Hibrida: "Híbrida"}

  before_create :clean_empty_space
 
  scope :find_jobs_by_title, ->(job) {
    includes(:users, :category, :users_jobs)
    .where('LOWER(title) LIKE ?', "%#{job.downcase}%")
    .order(id: :desc) if job.present?
  }

  
  scope :find_jobs_by_user_owner, ->(user) {
    includes(:users, :category, :users_jobs)
    where(user_id: user.id)
    .order(id: :desc)
  }

  scope :find_jobs_by_id_greater_than, ->(job) { where('id <= ? ',job.id).order(id: :desc) }
  
  scope :find_jobs_by_category_id, ->(category_id) { 
    includes(:users, :category, :users_jobs)
    .where('category_id = ?', category_id.to_i)
    .order(id: :desc) 
  }


  scope :find_jobs_ordered_by_id_desc, -> { 
      includes(:users, :category, :users_jobs)
      .order(id: :desc) 
  }

  scope :find_job_by_id, ->(job_params) { where(id: job_params) }
  
  scope :find_by_claimed, ->(claimed) { where(claimed: claimed) }
  
  scope :find_by_claimed, ->(claimed) { where(claimed: claimed) }
  
  scope :find_by_claimed_and_count, ->(claimed) { where(claimed: claimed).count }

  private 
    def clean_empty_space
      self.title = title.strip             
      puts "#############empty space cleaned"
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :my_opportunities]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_job

  include JobsConcern
  include JobsViewsConcern
  include UserConcern

  def search 
    @jobs ||= Job.find_jobs_by_title(params[:job]).page(params[:page]).per(8)
    @page_name_index = page_name("index")
  end
  
  def search_with_category
    @jobs ||= Job.find_jobs_by_category_id(params[:category_id]).page(params[:page]).per(8)
    @page_name_index = page_name("index")
 
    render "jobs/search", job: @jobs
  end

  def index
    @jobs ||= Job.find_jobs_ordered_by_id_desc.page(params[:page]).per(8)
    @page_name_index = page_name("index")
  end

  def my_opportunities
    @jobs ||= Job.find_jobs_by_user_owner(current_user).page(params[:page]).per(8)
  end

  # GET /jobs/1 or /jobs/1.json
  def show
    @page_name_index = page_name("show")
  end

  # GET /jobs/new
  def new
    if user_signed_in?
      if user_is_a_company_or_admim?(current_user)
        @job = Job.new
        @categories = Category.all
      else
        flash[:alert] = "O teu tipo de usuário não permite criar uma vaga."
        redirect_to jobs_path
      end
       
    else
      redirect_to new_user_session_path
    end
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    
    respond_to do |format|
      if @job.save!

        @candidates = User.find_by_category_id( @job.category_id )
        
        if @candidates.any?
          #Send email notification
          NotificationJob.perform_later(@job.id)
        end

        format.html { redirect_to job_url(@job), notice: "Oportunidade criada com sucesso." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update!(job_params)

       @candidates = User.find_by_category_id( @job.category_id )
        
        if @candidates.any?
          #Send email notification
          NotificationJob.perform_later(@job.id)
        end
        
        format.html { redirect_to job_url(@job), notice: "Oportunidade actualizada com sucesso." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Oportunidade eliminada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def invalid_job
      logger.error "Attempt to access invalid job #{params[:id]}"
      redirect_to jobs_url, info: "Vaga de emprego invalida."
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :type_job, :content, :salary, :category_id )
    end

end

app/helpers/jobs_helper.rb
module JobsHelper
    def is_the_owner_of_the_job?(job)
       (user_signed_in?) and (job.user_id == current_user.id)
    end

    def is_jobs_controller?
      controller.controller_name == "jobs"
    end


     def get_user_by_job(job)
       return User.find(job.user_id)
     end

     def truncated_html(text_with_html)
      truncate_html(text_with_html.to_s, length: 400 )
     end


     def reduce_the_duration_of_the_job(job)
       job.number_days -= 1
       job.updated_at = Time.now
       
       job.update!(job.attributes)
       
     end

     def number_of_days_is_zero?(job)
       job.number_days == 0
     end

     def delete_job_automatically(job)
       if number_of_days_is_zero?(job)
         job.delete!(job) 
         redirect_to jobs_path
       elsif !date_initial_is_equal_to_date_final?(job)
        reduce_the_duration_of_the_job(job)
       end
     end

     def date_initial_is_equal_to_date_final?(job)
        date_initial = (job.updated_at).to_s[0..9]
        date_final = (Time.now).to_s[0..9]
        
        return date_initial == date_final 
     end


end

app/views/jobs/_form.html.erb
<%= bootstrap_form_for(job) do |form| %>
  <% if job.errors.any? %>
    <div class="row d-flex justify-content-center">
        <div class="col-sm-9">
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
          
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

          <ul>
            <% job.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  <% end %>


<main class="container col-lg-6 my-4">
  <div class="card">
    <div class="card-body">
      <div class="card-title">
      	<h4 class="text-center">Postar Vaga</h4>
      </div>
      <div class="row my-2">

      <%= form.text_field :title, label: "Titulo", placeholder:"Título", class:"form-control" %>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name, { label: "Categória"}  %>
		  <%= form.select :type_job, Job.type_jobs, { label: "Local"} %>
		  <%= form.number_field :salary, label:"Salário", placeholder:"$ 00" %>
		  <%= form.text_area :content, label:"Descrição", size: "100x10", placeholder: "Descreve o detalhe da oportunidade. Ex: A empresa X está a contratar candidatos com habilidade Y para trabalhar como K..." %>

		<div class="mb-3 d-grid gap-2">
      <%= form.submit "Postar Vaga", class:"btn btn-success" %>
		</div>
      </div>
  </div>
</main>

<% end %>

app/views/jobs/_job.html.erb
  <div class="card" >
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h5 class="card-title"> <i class="bi-briefcase-fill"></i> <%= job.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">
            <i class="bi-tags-fill"></i> <%= job.category.name %>, 
            <i class="bi-geo-alt-fill"></i> <%= job.type_job %>
          </h6>
        </div>
        <div class="col">
          <% if user_have_applied?(job) %>
          <strong class="text-success"> Você já se candidatou a está vaga</strong>
          <% end %>
          <% if is_the_owner_of_the_job?(job) %>
              <% if exist_any_candidates?(job) %>

              <%= link_to "Ver todos os candidatos", candidates_users_job_path(job), class:"btn btn-outline-success my-1 col-sm-12" %>

              <% else %>
                <strong class="text-danger">Não existe nenhum candidato para este vaga</strong>
              <% end %>
          <% end %>

        </div>
      </div>

      <% delete_job_automatically(job)  %>

      <div class="row">
        
        <div class="col-sm-3">
          <% user = get_user_by_job(job) %>
          <div class="d-block">
            <%= display_user_image(user)%> 
          </div>
          <div class="d-block">
            <span class="badge rounded-pill bg-success col-sm-10"> Candidatos <%= job.applayers %></span>

          </div>

          <% if job.number_days > 10%>
          <div class="d-block">
            <span class="badge rounded-pill bg-warning text-black col-sm-10"> <%= job.number_days %> dias para encerrar a vaga</span>
          </div>
          <% else %>
          <div class="d-block">
            <span class="badge rounded-pill bg-danger col-sm-10"> <%= job.number_days %> dias paraencerrar a vaga</span>
          </div>
          <% end %>
          
          
        </div>


        <div class="col">
          <% if @page_name_index %>
            <p class="card-text" ><%=  truncated_html(job.content) %></p>
          
            
          <% else %>
            <p class="card-text" ><%= job.content %></p>
          <% end %>
          

          <% if @page_name_index %>
            <%= link_to "Mostrar está oportunidade", job, class:"btn btn-outline-primary my-1" %>
          <% end %>

          <% if user_have_applied?(job) %>
      
            <%= button_to "Retirar a minha candidatura", destroy_users_job_path(job), class:"btn btn-outline-danger my-1" %> 

          <% elsif !is_the_owner_of_the_job?(job) %>
             <%= link_to "Candidatar-me agora", apply_users_job_path(job), class:"btn btn-success my-1" %>  
          <% end %>


          <% if is_the_owner_of_the_job?(job) or is_admin?(job)%>

            <%= link_to "Editar está oportunidade", edit_job_path(job), class:"btn btn-warning my-1" %>
            
            <%= button_to "Eliminar está oportunidade", job, method: :delete, class:"btn btn-outline-link my-1", form:{ data: { turbo_confirm: "Tens a certeza?"} }  %>
          <% end %>
          <% if !job.claimed %>
            <%= link_to "Este conteúdo não devia estar nesta página ou site.", 
            back_lists_job_complaint_path(job), class:"btn btn-outline-warning my-1" %>
          <% end %>
        </div> 
      </div>

    </div>
  </div>

 <br>

app/views/jobs/edit.html.erb
<h3>Editar oportunidade</h3>
<%= turbo_frame_tag "job" do %>
  <%= render "form", job: @job %>
<% end %>

app/views/jobs/index.html.erb
<h3>Oportunidades</h3>

<div class="container col-sm-9" id="jobs">
  
    <% @jobs.each do |job| %>
        <%= render job %>
    <% end %>
    <div class="d-flex justify-content-center">
        <%= paginate @jobs, windows:2 %>
    </div>
    
</div>

app/views/jobs/my_opportunities.html.erb
<h3>Oportunidades</h3>

<div class="container col-sm-9" id="jobs">
  
    <% @jobs.each do |job| %>
        <%= render job %>
    <% end %>
    <div class="d-flex justify-content-center">
        <%= paginate @jobs, windows:2 %>
    </div>
    
</div>

app/views/jobs/new.html.erb
<%= turbo_frame_tag "job" do %>
    <%= render "form", job: @job %>
<% end %>

app/views/jobs/search.html.erb
<h3>Oportunidades</h3>


<div class="container col-sm-9" id="jobs">
    <%= turbo_frame_tag "job" do %>
        <% if @jobs.any? %>
            <% @jobs.each do |job| %>
                <%= render job %>
            <% end %>
            <div class="d-flex justify-content-center">
                <%= paginate @jobs, windows:2 %>
            </div>
        <% else %>
            <h3> Nenhuma oportunidade encontrada </h3>
        <% end %>
    <% end %>
</div>

app/views/jobs/show.html.erb
<div class="container col-sm-9" id="jobs">
  <%= turbo_frame_tag "job" do %>
    <%= render @job %>
  <% end %>
</div>