config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get "dashboad/index"

  resources :experiences
  mount Resque::Server.new, :at => "/resque"
  
  resources :rooms do 
    resources :messages
  end
  
  resources :users_jobs, only: [:index, :create] do 
    member do 
      get "apply"
      get "candidates"
      get "show"
      post "destroy", as: "destroy"
    end

  end

  resources :jobs do
    collection do 
      get "search" 
      get "search_with_category"
      get "my_opportunities"
    end 
  end
  
  resources :categories 

  devise_for :users, controllers: {registrations: "registrations"}
  root "home#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  get "back_lists/:id_job/job_create", 
    to: "back_lists#job_create", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "job_create"
  
  get "back_lists/:id_publicity/publicity_complaint", 
    to: "back_lists#publicity_complaint", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "back_lists_publicity_complaint"

    
  get "back_lists/:id_job/job_complaint", 
  to: "back_lists#job_complaint", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_job_complaint"

  
  get "back_lists/publicities", 
  to: "back_lists#publicities", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_publicities"

  get "back_lists/jobs", 
  to: "back_lists#jobs", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_jobs"

  get "back_lists", 
  to: "back_lists#index", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists"
  
   
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  validates_presence_of :start_date, :company_name, :profission, :end_date, :description
 
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /experiences or /experiences.json
  def index
    @experiences = Experience.includes(:user).where(user_id: current_user.id)
  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences or /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.destroy!

    respond_to do |format|
      format.html { redirect_to experiences_path, status: :see_other, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:company_name, :profission, :start_date, :end_date, :description, :user_id)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<div id="<%= dom_id experience %>">
  

<main class="container col-lg-6 my-4">
  <div class="card">
    <div class="card-body">
      <div class="card-title">
      	<h4 class="text-center"><%= experience.company_name %></h4>
      </div>
      <div class="row my-2">
          <p>
            <strong>Profission:</strong>
            <%= experience.profission %>
          </p>

          <p>
            <strong>Start date:</strong>
            <%= experience.start_date %>
          </p>

          <p>
            <strong>End date:</strong>
            <%= experience.end_date %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= experience.description %>
          </p>


      </div>
          <div class="mb-3 d-grid gap-2">
            <%= link_to "Edit", edit_experience_path(experience), class: "btn btn-info" %>
            
            <%= link_to "Ver todas as experiences", experiences_path, class: "btn btn-warning" %>
                        
            <%= link_to "Cadastar uma nova experiência", new_experience_path, class: "text-center text-info" %>
            
            <%= button_to "Eliminar", experience, 
            method: :delete, class:"btn btn-outline-link my-1", 
            form:{ data: { turbo_confirm: "Tens a certeza?"} }  %>
      
          </div>


      </div>
  </div>
</main>

app/views/experiences/_form.html.erb
<%= bootstrap_form_for(experience) do |form| %>
  <% if experience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <main class="container col-lg-6 my-4">
    <div class="card">
      <div class="card-body">

        <div class="row my-2">

          <%= form.text_field :company_name %>
          <%= form.text_field :profission %>

          <%= form.date_field :start_date %>
          <%= form.date_field :end_date %>

          <%= form.text_area :description, label:"Descrição", size: "100x10", 
          placeholder: "Descreve o detalhe da oportunidade. A tua experiencia." %>
  
          <%= form.hidden_field :user_id, value: current_user.id if current_user.present? %>
        
          <div class="mb-3 d-grid gap-2">
            <%= form.submit "Salvar", class:"btn btn-success" %>
          </div>
        </div>
    </div>
  </main>

<% end %>

  

app/views/experiences/edit.html.erb
<% content_for :title, "Editing experience" %>

<p class="text-center fs-4 text-success"> Editar experiências </p> 

<%= render "form", experience: @experience %>

app/views/experiences/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Experiences" %>

<p class="text-center fs-4 text-success"> Experiências </p> 

<div id="experiences">
  <% if @experiences.empty? %>
    <div class="container text-center">
      <%= link_to "Cadastar uma nova experiência", new_experience_path, class: "text-info" %>
    </div>
  <% else %>
  
    <% @experiences.each do |experience| %>
      <%= render experience %>
    <% end %>
  
  <% end %>
</div>

app/views/experiences/new.html.erb
<% content_for :title, "New experience" %>

<p class="text-center fs-4 text-success"> Nova Experiência </p> 

<%= render "form", experience: @experience %>

app/views/experiences/show.html.erb
<%= render @experience %>