config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get "dashboad/index"

  resources :experiences
  mount Resque::Server.new, :at => "/resque"
  
  resources :rooms do 
    resources :messages
  end
  
  resources :users_jobs, only: [:index, :create] do 
    member do 
      get "apply"
      get "candidates"
      get "show"
      post "destroy", as: "destroy"
    end

  end

  resources :jobs do
    collection do 
      get "search" 
      get "search_with_category"
      get "my_opportunities"
    end 
  end
  
  resources :categories 

  devise_for :users, controllers: {registrations: "registrations"}
  root "home#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  get "back_lists/:id_job/job_create", 
    to: "back_lists#job_create", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "job_create"
  
  get "back_lists/:id_publicity/publicity_complaint", 
    to: "back_lists#publicity_complaint", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "back_lists_publicity_complaint"

    
  get "back_lists/:id_job/job_complaint", 
  to: "back_lists#job_complaint", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_job_complaint"

  
  get "back_lists/publicities", 
  to: "back_lists#publicities", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_publicities"

  get "back_lists/jobs", 
  to: "back_lists#jobs", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_jobs"

  get "back_lists", 
  to: "back_lists#index", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists"
  
   
end

app/models/room.rb
class Room < ApplicationRecord
  attr_accessor :candidate_id
  
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_one :invite, dependent: :destroy

  scope :find_rooms_by_user, ->(room) { where(user_id: room.user_id)}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_rooms

  include RoomConcern
  include UserConcern

  # GET /rooms or /rooms.json
  def index

    if user_is_a_company_or_admim?(current_user) 
      @rooms = Room.includes(:user, :messages)
                   .where(user_id: current_user.id)
    else
      @invites = Invite.find_invites_candidate(current_user).to_a
    end
  
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    # varible @invites should be invite
    @invites = Invite.find_by_room(set_room)
    
    if current_user.Candidato? and @invites.present?
      @invites.update!(opened: true)
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
         create_invite(@room, room_params[:candidate_id])
       
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
   
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def invalid_rooms
    logger.error "Attempt to access invalid user: #{params[:id]}"
    redirect_to jobs_url, info: "Usuário ou sala de conversa não encontrada."
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find_by(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:user_id, :candidate_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def is_rooms_controller?
	  controller.controller_name == "rooms"
	end
end

app/views/rooms/_form.html.erb
<%= bootstrap_form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div class="row d-flex justify-content-center">
        <div class="col-sm-9">
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
          
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

       <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
       </ul>
        </div>
      </div>
    </div>
  <% end %>

  <main class="container col-lg-6 my-4">
  <div class="card">
    <div class="card-body">
      <div class="card-title">
        <h4 class="text-center">Iniciar uma conversa</h4>
      </div>
      <div class="row my-2">
        <%= form.text_field :user_id, value: current_user.id if current_user.present? %>
        <%= form.text_field :candidate_id, value: 2 %>

    <div class="mb-3 d-grid gap-2">
      <%= form.submit "Iniciar agora", class:"btn btn-success" %>
    </div>
      </div>
  </div>
</main>

<% end %>

app/views/rooms/_room.html.erb
  <div class="row" id="<%= dom_id room %>">

   
      <div class="col-sm-1">
        <%= link_to room do %>
         <%= display_user_image_profile(room.user) %>
        <% end %>
      </div>
      
        <div class="col">
          <% candidate = InvitesHelper::User.new(room) %>
          <%= link_to room, class:"link-success" do %>
            <strong>@<%= candidate.username %></strong> <br>
            <strong><%= candidate.email %></strong> 
          <% end %>
        </div>
      
      <% if !room.invite.opened? %>
        <div class="col d-flex justify-content-center">
          <strong class="text-danger">Novo convite</strong>
        </div>
      <% end %>
      <div class="col d-flex justify-content-end">
       <%= button_to room, method: :delete, class:"btn btn-danger my-1", form:{ data: { turbo_confirm: "Todas as conversas contidas neste chat serão eliminadas. Tens a certeza que pretendes eliminar?"} }  do %>
        <i class="bi bi-trash-fill"></i>
       <% end %>

      </div>
 
    

  </div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render "form", room: @room %>
<% end %>
  <br>

  <div>
    <%= link_to "Show this room", @room %> |
    <%= link_to "Back to rooms", rooms_path %>
  </div>

app/views/rooms/index.html.erb
<div class="container col-sm-9 my-2">
  
  <div class="card">
    <div class="card-header">
      <% if user_is_admin_or_company?(current_user) %>
      <h5 class="card-title text-center">Meus chats com os candidatos</h5>
      <% else %>
      <h5 class="card-title text-center">Meus chats com as empresas</h5>
      <% end %>
    </div>

    <div class="card-body" id="rooms">
     <!-- #if !@rooms.present? -->
        <h3 class="text-center"> Sem nenhum convite!</h3>
      <% if user_is_admin_or_company?(current_user) %>
        <% @rooms.each do |room| %>
          <% if room.invite.present? %>
              <p>
                <%= render room %>
              </p>
                <hr/>
          <% end %>
        <% end %>
        <% elsif !user_is_admin_or_company?(current_user) %>
          <% @invites.each do |invite| %>
            <% if invite.room.present? %>
              <p>
                <%= render invite.room %>

              </p>
                <hr/>

            <% end %>
          <% end %>

      <% end %>
    </div>
  </div>

</div>

app/views/rooms/new.html.erb
<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<div class="container col-sm-4">
  
<div class="card">
  <% if user_signed_in? %>
    <% if user_is_admin_or_company?(current_user)%>
      <h5 class="card-header">
        <% @invite = @invites %>
        <%= chat_image(@invite.user) %>
        Chat com candidato <%= @invite.user.username if @room.present? %>
      </h5>
    <% else %>
         <h5 class="card-header">Chat com a Empresa <%= @room.user.username if @room.present? %></h5>
    <% end %>
  <% end %>
  <div class="card-body" id="overflow-chat">


      <%= turbo_stream_from @room %>

      <%= turbo_frame_tag "room" do %>

        <div class="d-grid gap-2 d-md-block">

          <ul class="nav justify-content-center">
            <li class="nav-item px-2">
              <%= link_to rooms_path, class:"btn btn-warning", "data-turbo-frame":"_top" do%>
               <i class="bi bi-people-fill"></i>
              <% end %>
              
            </li>
            <li class="nav-item">
              <%= button_to @room, class:"btn btn-danger", 
                form:{ data: { turbo_confirm: "Está acção vai eliminar toda a conversa com este candidato(a). Tens a certeza que pretendes eliminar?"} },
                method: :delete do %>

                <i class="bi bi-trash-fill"></i>

              <% end %>
            </li>
          </ul>

        </div>
        <hr/>
      <% end %>

      <div id="messages">
        <%= render @room.messages %>
      </div>

      
    </div>
    <%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>
  </div>
</div>