config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  get "dashboad/index"

  resources :experiences
  mount Resque::Server.new, :at => "/resque"
  
  resources :rooms do 
    resources :messages
  end
  
  resources :users_jobs, only: [:index, :create] do 
    member do 
      get "apply"
      get "candidates"
      get "show"
      post "destroy", as: "destroy"
    end

  end

  resources :jobs do
    collection do 
      get "search" 
      get "search_with_category"
      get "my_opportunities"
    end 
  end
  
  resources :categories 

  devise_for :users, controllers: {registrations: "registrations"}
  root "home#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  get "back_lists/:id_job/job_create", 
    to: "back_lists#job_create", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "job_create"
  
  get "back_lists/:id_publicity/publicity_complaint", 
    to: "back_lists#publicity_complaint", 
    constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
    as: "back_lists_publicity_complaint"

    
  get "back_lists/:id_job/job_complaint", 
  to: "back_lists#job_complaint", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_job_complaint"

  
  get "back_lists/publicities", 
  to: "back_lists#publicities", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_publicities"

  get "back_lists/jobs", 
  to: "back_lists#jobs", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists_jobs"

  get "back_lists", 
  to: "back_lists#index", 
  constraints: { id: /[A-Z][A-Z][0-9]+/ }, 
  as: "back_lists"
  
   
end

app/views/layouts/_about.html.erb
  <section class="text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1>Bumbagora</h1>
        <p class="lead text-success">
Somos uma empresa angolana que nasceu em 2022, atuando na área de desenvolvimento de software, consultoria e vendas gerando valores para os nossos clientes. </p>
        <p>
        <% if !user_signed_in? %>    
          <div class="d-grid gap-2">
            <%= link_to "Criar conta", new_user_registration_path, class: "btn btn-outline-success my-2" %>
          </div>
        <% end %>
        </p>
      </div>
    </div>
  </section>

app/views/layouts/_alert.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light teal-darken-3">
  <p class="text-white text-center"> Conheça o CTO e CIO da empresa.</p>
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/PlusVicente"> 
          <i class="bi-twitter footer-icon"></i> 
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/Vicente-jpro"> 
          <i class="bi-github footer-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.linkedin.com/in/vicente-sim%C3%A3o-504287160/"> 
          <i class="bi-linkedin text-white footer-icon"></i>
        </a>
      </li>
    </ul>
  </div>
  <p class="text-center text-white">
    ©2022 - Bumbagora | Direitos reservados
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-color fixed-top teal-darken-3">

      <div class="container">
        <%= link_to "Bumbagora", root_path, class:"navbar-brand text-white" %> 
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          
          <span class=" d-block navbar-toggler-icon"></span>
          <span class=" d-block navbar-toggler-icon"></span>
          <span class=" d-block navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Ver vagas", jobs_path, class: "nav-link", "data-turbo-frame": "_top" %>
            </li>
            <li class="nav-item">
               
            <%= link_to "Postar Vaga", new_job_path, class: "nav-link" %>

            </li>

            <% if user_signed_in? %>

              <li class="nav-item">
                <% if user_is_admin_or_company?(current_user) %>
                  <%= link_to "Minhas oportunidades", my_opportunities_jobs_path, class: "nav-link", "data-turbo-frame": "_top" %>
                  <% else %>
                  <%= link_to "Candidaturas", users_jobs_path, class: "nav-link", "data-turbo-frame": "_top" %>
                  <% end %>
              </li>

              <% if current_user.Admin? %>
                <li class="nav-item">
                  <%= link_to "Dashboard", dashboad_index_path, class: "nav-link" %>
                </li>
              <% end %>

            <% end %>

          </ul>
          <ul class="nav justify-content-end ">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to rooms_path, class:"nav-link" do %>
              <button type="button" class="btn btn-transparent position-relative">
                <i class="bi-chat-left-text text-white "></i>
                <% if @invite.present? %>
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">

                    <!-- Show number of messages -->
                    <% if user_is_admin_or_company?(current_user) %>
                      <%= find_and_count_candidate_messages_with_room(@invite.room) %>
                    <% else %>
                      <%= find_and_count_company_messages_with_room(@invites) %>
                    <% end %>
                    <!-- End show number of messages -->
                    
                    <span class="visually-hidden">unread messages</span>
                 <% elsif candidate_has_invite?(current_user) %>
                
                   <span class="position-absolute top-0 start-100 translate-middle p-2 pink-lighten-4  rounded-circle">
                      <span class="visually-hidden">New alerts</span>
                   </span>
                   <% else %>
                    <span class="position-absolute top-0 start-100 translate-middle p-2 teal-lighten-5  rounded-circle">
                      <span class="visually-hidden">New alerts</span>
                   </span>
                   
                 <% end %>
                </span>
              </button>
              <% end %>
            </li>
              
            </li>
            <li class="nav-item">
            <%= link_to "Perfil", edit_user_registration_path, class: "nav-link"%>
            </li>
              <li class="nav-item ">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete,  class: "nav-link btn btn-outline-light" %>
            </li>
            <% else %>
              <li class="nav-item "> 
              <%= link_to "Criar conta", new_user_registration_path, class: "nav-link " %>
              
            </li>
              <li class="nav-item">
              <%= link_to "Entrar", new_user_session_path, class: "nav-link btn btn-outline-light"%>
            </li>
            <% end %>
        </ul>
        </div>
      </div>
  </nav>
</header>

app/views/layouts/_info.html.erb
<br>
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= info %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_message.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <i class="bi-check-circle-fill" ></i>
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_search_bar.html.erb
<div class="container my-4">

    <div class="row d-flex justify-content-center">
        <div class="col text-center d-flex justify-content-center" >
            <form action="/jobs/search" class="d-flex col-sm-9">
                <input class="form-control me-2" type="search" name="job" placeholder="Pesquisar oportunidades por título." aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Pesquisar</button>
            </form>
        </div>
    </div>
      
</div>

app/views/layouts/_search_check.html.erb
<div class="container my-4">
    <div class="row d-flex justify-content-center">
      <div class="col my-1">
      	<div class="col text-center d-flex justify-content-center" >

         <%= bootstrap_form_tag url: "/jobs/search_with_category", method: :get do |form| %>

            <%= form.collection_select :category_id, Category.order(:name), :id, :name, {label: "Seleciona uma categoria"} %>
            <%= form.submit "Pesquisar pela categória selecionada", class:"btn btn-success" %>
         <% end %>
       </div>
      </div>
    </div>


      
</div>

app/views/layouts/_search_select.html.erb
<div class="container my-4">
    <div class="row d-flex justify-content-center">
      <div class="col my-1">
      	<div class="col text-center d-flex justify-content-center" >

         <%= bootstrap_form_tag url: "/jobs/search_with_category", method: :get do |form| %>

            <%= form.collection_select :category_id, Category.order(:name), :id, :name, {label: "Seleciona uma categoria"} %>
            <%= form.submit "Pesquisar pela categória selecionada", class:"btn btn-success" %>
         <% end %>
       </div>
      </div>
    </div>


      
</div>

app/views/layouts/_service.html.erb
<div class="text-center my-5 teal-lighten-5">
  <div class="container" id="service">
    <h3>Nossos Serviços</h3>
    <div class="row justify-content-center">
      <div class="col-sm-4 ">
        <div class="d-inline p-2 ">
          <i class="bi bi-code-slash i-large"></i><br>
        </div>
        <div class="d-inline p-2">
          <p class="i-description"> Desenvolvemos sistemas, plataformas ou aplicativos para o seu negócio. Contamos com profissionais capacitados.</p>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="d-inline p-2 ">
          <i class="bi bi-gear-fill i-large"></i><br>
        </div>
        <div class="d-inline p-2">
           <p class="i-description"> Realizamos o teu sonho de ser o seu próprio gestor dos teus softwares ou plataforma de negócios para aumentar a tua renda. </p>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="d-inline p-2 ">
          <i class="bi bi-headset i-large"></i><br>
        </div>
        <div class="d-inline p-2">
           <p class="i-description"> Somos uma consultora de desenvolvimento de software que atua especificamente com Ruby on Rails.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <title>Bumbagora - Emprego em Angola | Desenvolviemto de Sistemas</title>
    <meta name="description" content="Bumbagora - Emprego em Angola | Desenvolviemto de Sistemas">
    <meta name="keywords" content="vagas de emprego em angola, criação de web site, criação de aplicatios, business intelligence, desenvolvimento de sistemas, soluções em ti, luanda angola, criação de sites, tecnologia da informação, vagas de emprego, bumbagora, ruby, ruby on rails, ruby angola, ruby on rails angola, vicente, vicente simao, vicente on rails, senhor ruby angola">
    <meta name="author" content="Vicente Simão">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="shortcut icon" type="image/x-icon" href="<%= image_path('Bumbagora.png')%>" />
 
   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/header'%>
    <main>
      <% if !is_rooms_controller? and !is_device_controller?%>
        <%= render 'layouts/search_select' if @page != "home" %>
        <%= render 'layouts/search_bar'%>
      <% end %>

      <%= render 'layouts/message' if notice %>
      <%= render 'layouts/alert' if alert %> 
      <%= render 'layouts/info' if info %>
      
      <% if @page == "home" %>
        <%= render 'layouts/about' %>
        <%= render 'layouts/service' %>
      <% end %>
      
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>